//! Fixtures de diseño: nunca se mezclan con una sesión real ni salen a la red.
pub(super) struct Player {
    pub name: &'static str,
    pub agent: &'static str,
    pub rank: &'static str,
    pub peak: &'static str,
    pub kd: &'static str,
    pub wr: &'static str,
    pub form: &'static str,
    pub hs: &'static str,
    pub adr: &'static str,
    pub hidden: bool,
    pub match_kda: (u32, u32, u32),
    pub match_acs: u32,
    pub match_hs: u32,
    pub premade: Option<u8>,
}

#[derive(Clone, Copy)]
pub(super) struct Match {
    pub map: &'static str,
    pub agent: &'static str,
    pub score: &'static str,
    pub won: bool,
    pub kills: u32,
    pub deaths: u32,
    pub assists: u32,
    pub rr: i32,
    pub acs: u32,
}

pub(super) struct Demo {
    pub players: Vec<Player>,
    pub rounds: Vec<(u32, Option<(u32, u32)>)>,
    pub matches: Vec<Match>,
    pub post: bool,
}

impl Default for Demo {
    fn default() -> Self {
        let rows = [
            (
                "Jugador 1",
                "Sova",
                "DIA 2",
                "1.18",
                "55%",
                "VVDVV",
                "26%",
                "152",
            ),
            (
                "Jugador 2",
                "Omen",
                "DIA 1",
                "1.06",
                "50%",
                "DVDVV",
                "22%",
                "138",
            ),
            (
                "Jugador 3",
                "Jett",
                "ASC 1",
                "1.31",
                "60%",
                "VVVDV",
                "31%",
                "167",
            ),
            (
                "Jugador 4",
                "Killjoy",
                "DIA 2",
                "0.98",
                "50%",
                "VDDVD",
                "24%",
                "126",
            ),
            (
                "Jugador 5",
                "Sage",
                "PLA 3",
                "1.02",
                "55%",
                "DVVDV",
                "21%",
                "132",
            ),
            (
                "Jugador 6",
                "Raze",
                "DIA 3",
                "1.22",
                "55%",
                "VVDDV",
                "27%",
                "160",
            ),
            ("Jugador 7", "Cypher", "—", "—", "—", "—", "—", "—"),
            (
                "Jugador 8",
                "Breach",
                "DIA 1",
                "1.09",
                "50%",
                "DVVDV",
                "23%",
                "142",
            ),
            (
                "Jugador 9",
                "Omen",
                "DIA 2",
                "1.14",
                "55%",
                "VDVDV",
                "25%",
                "148",
            ),
            (
                "Jugador 10",
                "Sova",
                "PLA 3",
                "0.96",
                "50%",
                "DDVVD",
                "20%",
                "129",
            ),
        ];
        let match_stats = [
            (18, 17, 6, 235, 29),
            (17, 17, 3, 211, 17),
            (21, 17, 5, 259, 34),
            (9, 18, 7, 131, 19),
            (21, 20, 11, 245, 28),
            (20, 19, 2, 238, 16),
            (30, 20, 8, 384, 20),
            (8, 18, 3, 100, 11),
            (18, 14, 8, 220, 34),
            (13, 15, 5, 172, 19),
        ];
        let premades = [
            Some(1),
            None,
            Some(1),
            Some(2),
            Some(2),
            Some(3),
            Some(4),
            Some(3),
            Some(4),
            Some(3),
        ];
        Self {
            players: rows
                .into_iter()
                .enumerate()
                .map(|(i, (name, agent, rank, kd, wr, form, hs, adr))| {
                    let (kills, deaths, assists, acs, match_hs) = match_stats[i];
                    Player {
                        name,
                        agent,
                        rank,
                        peak: match i {
                            2 | 5 => "INM 1",
                            6 => "—",
                            _ => "ASC 1",
                        },
                        kd,
                        wr,
                        form,
                        hs,
                        adr,
                        hidden: i == 6,
                        match_kda: (kills, deaths, assists),
                        match_acs: acs,
                        match_hs,
                        premade: premades[i],
                    }
                })
                .collect(),
            rounds: vec![
                (1, Some((1, 1))),
                (2, Some((0, 1))),
                (3, Some((2, 0))),
                (4, Some((1, 1))),
                (5, Some((4, 0))),
                (6, Some((0, 1))),
                (7, None),
            ],
            matches: vec![
                Match {
                    map: "Ascent",
                    agent: "Sova",
                    score: "13:9",
                    won: true,
                    kills: 27,
                    deaths: 15,
                    assists: 8,
                    rr: 19,
                    acs: 264,
                },
                Match {
                    map: "Haven",
                    agent: "Omen",
                    score: "8:13",
                    won: false,
                    kills: 14,
                    deaths: 18,
                    assists: 6,
                    rr: -16,
                    acs: 186,
                },
                Match {
                    map: "Bind",
                    agent: "Sova",
                    score: "13:11",
                    won: true,
                    kills: 18,
                    deaths: 19,
                    assists: 10,
                    rr: 17,
                    acs: 209,
                },
                Match {
                    map: "Lotus",
                    agent: "Killjoy",
                    score: "13:7",
                    won: true,
                    kills: 21,
                    deaths: 12,
                    assists: 7,
                    rr: 18,
                    acs: 238,
                },
                Match {
                    map: "Sunset",
                    agent: "Sova",
                    score: "10:13",
                    won: false,
                    kills: 17,
                    deaths: 20,
                    assists: 5,
                    rr: -18,
                    acs: 201,
                },
                Match {
                    map: "Abyss",
                    agent: "Omen",
                    score: "13:5",
                    won: true,
                    kills: 24,
                    deaths: 10,
                    assists: 9,
                    rr: 21,
                    acs: 276,
                },
                Match {
                    map: "Icebox",
                    agent: "Sova",
                    score: "11:13",
                    won: false,
                    kills: 19,
                    deaths: 18,
                    assists: 6,
                    rr: -15,
                    acs: 224,
                },
                Match {
                    map: "Ascent",
                    agent: "Killjoy",
                    score: "13:10",
                    won: true,
                    kills: 16,
                    deaths: 14,
                    assists: 11,
                    rr: 17,
                    acs: 190,
                },
                Match {
                    map: "Haven",
                    agent: "Omen",
                    score: "9:13",
                    won: false,
                    kills: 15,
                    deaths: 19,
                    assists: 8,
                    rr: -17,
                    acs: 181,
                },
                Match {
                    map: "Bind",
                    agent: "Sova",
                    score: "13:6",
                    won: true,
                    kills: 22,
                    deaths: 11,
                    assists: 10,
                    rr: 20,
                    acs: 251,
                },
                Match {
                    map: "Lotus",
                    agent: "Sova",
                    score: "13:11",
                    won: true,
                    kills: 20,
                    deaths: 17,
                    assists: 7,
                    rr: 16,
                    acs: 230,
                },
                Match {
                    map: "Sunset",
                    agent: "Killjoy",
                    score: "7:13",
                    won: false,
                    kills: 12,
                    deaths: 20,
                    assists: 6,
                    rr: -19,
                    acs: 155,
                },
                Match {
                    map: "Abyss",
                    agent: "Omen",
                    score: "13:8",
                    won: true,
                    kills: 23,
                    deaths: 13,
                    assists: 8,
                    rr: 19,
                    acs: 266,
                },
                Match {
                    map: "Icebox",
                    agent: "Sova",
                    score: "13:4",
                    won: true,
                    kills: 25,
                    deaths: 9,
                    assists: 6,
                    rr: 22,
                    acs: 289,
                },
                Match {
                    map: "Ascent",
                    agent: "Omen",
                    score: "12:14",
                    won: false,
                    kills: 18,
                    deaths: 20,
                    assists: 9,
                    rr: -16,
                    acs: 215,
                },
                Match {
                    map: "Haven",
                    agent: "Sova",
                    score: "13:9",
                    won: true,
                    kills: 21,
                    deaths: 15,
                    assists: 12,
                    rr: 18,
                    acs: 244,
                },
                Match {
                    map: "Bind",
                    agent: "Killjoy",
                    score: "13:2",
                    won: true,
                    kills: 19,
                    deaths: 8,
                    assists: 9,
                    rr: 20,
                    acs: 235,
                },
                Match {
                    map: "Lotus",
                    agent: "Omen",
                    score: "8:13",
                    won: false,
                    kills: 14,
                    deaths: 19,
                    assists: 7,
                    rr: -18,
                    acs: 176,
                },
                Match {
                    map: "Sunset",
                    agent: "Sova",
                    score: "13:11",
                    won: true,
                    kills: 22,
                    deaths: 16,
                    assists: 8,
                    rr: 17,
                    acs: 248,
                },
                Match {
                    map: "Abyss",
                    agent: "Killjoy",
                    score: "10:13",
                    won: false,
                    kills: 16,
                    deaths: 18,
                    assists: 10,
                    rr: -15,
                    acs: 194,
                },
            ],
            post: false,
        }
    }
}
